version: "3.9"
services:
  redis:
    restart: unless-stopped
    build: ./redis
    expose:
      - 8081
    ports:
      - 8081:8081
  api:
    restart: unless-stopped
    build: ./server
    env_file: ./server/.env
    expose:
      - 8080
    ports:
      - 8080:8080
    depends_on:
      - redis
