version: "3.9"
services:
  api:
    restart: unless-stopped
    build: ./server
    env_file: ./server/.env
  nginx:
    image: nginx:1.23
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
