version: "3.9"
services:
  api:
    restart: unless-stopped
    build: ./server
    env_file: ./server/.env
    depends_on:
      - redis
  redis:
    image: "bitnami/redis:latest"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  nginx:
    image: nginx:stable
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
